# Generated by Django 2.2 on 2019-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='char',
            field=models.CharField(choices=[('rogue', 'rogue'), ('ork', 'ork'), ('grandpa', 'grandpa')], default='rogue', max_length=255),
        ),
    ]
