# Generated by Django 2.1.5 on 2019-12-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='char',
            field=models.CharField(choices=[('rogue', 'rogue'), ('ork', 'ork'), ('grandpa', 'grandpa')], default='rogue', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Room'),
        ),
    ]
